### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pool'

### ISSUE THREAD

**Issue by ohlmic** [Octavian-ai/english2cypher#12]
Hi,

This seems as such a great repo! I'm trying to build a chatbot with Neo4j as a knowledge graph so I was looking for a good NLU-module.

However, when trying to run python -m e2c.predict (following the instructions and using Docker and ./start-neo4j-database.sh which works just fine) I encounter the following error:

Traceback (most recent call last):
  File "/Users/michaelohlsson/opt/anaconda3/envs/e2c/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/michaelohlsson/opt/anaconda3/envs/e2c/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michaelohlsson/Documents/ML/jobb/FK-graphDB/english2cypher-master/e2c/predict.py", line 118, in <module>
    with Neo4jSession(args) as session:
  File "/Users/michaelohlsson/Documents/ML/jobb/FK-graphDB/english2cypher-master/db/execute.py", line 24, in __enter__
    encrypted=False)
  File "/Users/michaelohlsson/.local/share/virtualenvs/english2cypher-master-iOmFRD4f/lib/python3.6/site-packages/neo4j/v1/api.py", line 88, in driver
    return Driver(uri, **config)
  File "/Users/michaelohlsson/.local/share/virtualenvs/english2cypher-master-iOmFRD4f/lib/python3.6/site-packages/neo4j/v1/api.py", line 127, in __new__
    return subclass(uri, **config)
  File "/Users/michaelohlsson/.local/share/virtualenvs/english2cypher-master-iOmFRD4f/lib/python3.6/site-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/Users/michaelohlsson/.local/share/virtualenvs/english2cypher-master-iOmFRD4f/lib/python3.6/site-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/Users/michaelohlsson/.local/share/virtualenvs/english2cypher-master-iOmFRD4f/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 458, in acquire_direct
    connection.pool = self
AttributeError: 'NoneType' object has no attribute 'pool'

It first prints everything up to the example questions before it breaks. 

Any idea what it could be? Have been searching but not found anything that has helped.

Cheers!

**Comment by ohlmic** [comment]
Sorry. This was a really simple problem of having a local neo4j running on my computer at the same time as running the Docker-command. After shutting down the local one, it now works:)
