### ISSUE TITLE
 No module named 'db'

### ISSUE THREAD

**Issue by prashanthkolaneru** [Octavian-ai/english2cypher#6]
(yourenvname) C:\Users\User>english2cypher-master\e2c\predict.py
Traceback (most recent call last):
  File "C:\Users\User\english2cypher-master\e2c\predict.py", line 23, in <module>
    from db import *
ModuleNotFoundError: No module named 'db'

**Comment by davidhughhenrymack** [comment]
Hello!

What version of python are you using? It sounds like maybe you’re using
Python < 3 and the system is not seeing the /db/ folder as a module.


On October 8, 2018 at 2:58:42 AM, raspberian1234 (notifications@github.com)
wrote:

(yourenvname) C:\Users\User>english2cypher-master\e2c\predict.py
Traceback (most recent call last):
File "C:\Users\User\english2cypher-master\e2c\predict.py", line 23, in
from db import *
ModuleNotFoundError: No module named 'db'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/english2cypher/issues/6>, or mute the thread

**Comment by prashanthkolaneru** [comment]
i am using python 3.6.4

**Comment by davidhughhenrymack** [comment]
Weird - what command line are you executing the app with?

python -m e2c.predict I /believe/ is the right incarnation


On October 8, 2018 at 8:44:05 AM, raspberian1234 (notifications@github.com)
wrote:

i am using python 3.6.4

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/english2cypher/issues/6#issuecomment-427883698>,
or mute the thread

**Comment by prashanthkolaneru** [comment]
i am using anaconda terminal and doing in virtual environment 
i downloaded file and copied in home directory

C:\Users\User>english2cypher-master\english2cypher-master\e2c\predict.py
Traceback (most recent call last):
  File "english2cypher-master\english2cypher-master\e2c\predict.py", line 23, in <module>
    from db import *
ModuleNotFoundError: No module named 'db'
got this problem

**Comment by davidhughhenrymack** [comment]
Ah - the problem is how you invoke the script. Don’t directly run
predict.py.

Check README.md for all the details, but basically you need to invoke
`python -m e2c.predict` to get the module environment correct


On October 8, 2018 at 9:14:08 AM, raspberian1234 (notifications@github.com)
wrote:

i am using anaconda and doing in virtual environment
i downloaded file and copied in home directory

C:\Users\User>english2cypher-master\english2cypher-master\e2c\predict.py
Traceback (most recent call last):
File "english2cypher-master\english2cypher-master\e2c\predict.py", line 23,
in
from db import *
ModuleNotFoundError: No module named 'db'
got this problem

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/english2cypher/issues/6#issuecomment-427893691>,
or mute the thread

**Comment by prashanthkolaneru** [comment]
hi

(english2cypher) C:\Users\User>git clone https://github.com/Octavian-ai/english2cypher.git
Cloning into 'english2cypher'...
remote: Enumerating objects: 437, done.
remote: Total 437 (delta 0), reused 0 (delta 0), pack-reused 437
Receiving objects: 100% (437/437), 10.70 MiB | 591.00 KiB/s, done.
Resolving deltas: 100% (300/300), done.

(english2cypher) C:\Users\User>python -m e2c.predict
C:\Users\User\Anaconda3\envs\english2cypher\python.exe: Error while finding module specification for 'e2c.predict' (ModuleNotFoundError: No module named 'e2c')

(english2cypher) C:\Users\User>
this is the problem i am facing

**Comment by davidhughhenrymack** [comment]
Try cd into “english2cypher” directory, then run the python command


On October 9, 2018 at 12:19:48 AM, raspberian1234 (notifications@github.com)
wrote:

hi

(english2cypher) C:\Users\User>git clone
https://github.com/Octavian-ai/english2cypher.git
Cloning into 'english2cypher'...
remote: Enumerating objects: 437, done.
remote: Total 437 (delta 0), reused 0 (delta 0), pack-reused 437
Receiving objects: 100% (437/437), 10.70 MiB | 591.00 KiB/s, done.
Resolving deltas: 100% (300/300), done.

(english2cypher) C:\Users\User>python -m e2c.predict
C:\Users\User\Anaconda3\envs\english2cypher\python.exe: Error while finding
module specification for 'e2c.predict' (ModuleNotFoundError: No module
named 'e2c')

(english2cypher) C:\Users\User>
this is the problem i am facing

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/english2cypher/issues/6#issuecomment-428087008>,
or mute the thread

**Comment by prashanthkolaneru** [comment]
C:\Users\User>cd C:\Users\User\english2cypher

C:\Users\User\english2cypher>python -m e2c.predict
C:\Users\User\Anaconda3\python.exe: No module named e2c.predict

i am not sure python -m e2c.predict is not python command

**Comment by davidhughhenrymack** [comment]
Weird, I’m not familiar with running this on Windows, so sorry to not be
more helpful.

Here’s my osx (e.g. Linux) workflow:

I’m running Python 3.6.2

On October 9, 2018 at 6:25:49 AM, raspberian1234 (notifications@github.com)
wrote:

C:\Users\User>cd C:\Users\User\english2cypher

C:\Users\User\english2cypher>python -m e2c.predict
C:\Users\User\Anaconda3\python.exe: No module named e2c.predict

i am not sure python -m e2c.predict is not python command

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/english2cypher/issues/6#issuecomment-428190628>,
or mute the thread

**Comment by prashanthkolaneru** [comment]
![image](https://user-images.githubusercontent.com/31656797/46683989-d08ec180-cc1b-11e8-810c-5e89738874ba.png) this error

2)i had set of questions and answers in a csv file
where i should put that file in your code
to generate english2cypher and give answer  as output.

**Comment by davidsketchdeck** [comment]
1) Make sure you're running the right version of tensorflow (check the pipfile)
2) Either follow the YAML format in /data or write some code to load your CSV directly :)
